name: one_blood
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  dots_indicator: ^1.2.0
  flare_flutter: ^2.0.6
  animations: ^1.1.2
  simple_animations: ^2.2.3
  font_awesome_flutter: ^8.10.0
  flutter_otp_text_field: ^0.0.1
  fab_circular_menu: ^1.0.0
  intl: ^0.16.1
  modal_progress_hud: ^0.1.3
  geolocator: ^6.1.6
  geocoding: ^1.0.5
  shimmer: ^1.1.2
  cool_alert: ^1.0.1
  expandable: ^4.1.4
  url_launcher: ^5.7.10
  audioplayers: ^0.13.5
  timelines: ^0.0.2+1

  #data providers
  provider: ^4.3.2+2


  #messenging
  firebase_messaging: ^7.0.3

  #auth services
  firebase_auth: ^0.18.1
  google_sign_in: ^4.5.4
  flutter_otp: ^0.3.2
  sms: ^0.2.0
  http: ^0.12.2
  #database services
  firebase_core: ^0.5.2
  cloud_firestore: ^0.14.3
  firebase_storage: ^5.1.0
  image_picker: ^0.6.7+14

  #map services
  google_maps_flutter: ^1.0.6
  flutter_map: ^0.10.1+1
  latlong: ^0.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/whole/
    - assets/flags/
    - assets/firstPage/
    - assets/
    - assets/user_avatars/
    - assets/reaction_emoji/
    - assets/sounds/
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
    - family: Limelight
      fonts:
        - asset: fonts/Limelight-Regular.ttf
        - asset: fonts/Norican-Regular.ttf
        - asset: fonts/Pattaya-Regular.ttf

